export const TRANSACTION_RELATION = 'transaction';
export const PLAYER_RELATION = 'player';
export const CURR_RELATION = 'currency';
export const BALANCE_RELATION = 'currbalance';
export const SHOP_RELATION = 'shop';
export const SHOPITEM_RELATION = 'shopitemsold';
export const ITEM_RELATION = 'item';
export const CATEGORY_RELATION = 'itemcategory';
export const INV_RELATION = 'inventory';
export const INVITEM_RELATION = 'inventoryitem';
export const COSMETIC_RELATION = 'cosmetic'; // have a rarity
export const CONSUMABLE_RELATION = 'consumable'; // have a expiration and description
export const SALES_RELATION = 'saleamount';
